// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJboCUpPOZx30g4QKIUjKvOhjvVG9jRQ8',
    appId: '1:271984737306:web:c0a90752896f1f982325a3',
    messagingSenderId: '271984737306',
    projectId: 'watchman-s-gazette',
    authDomain: 'watchman-s-gazette.firebaseapp.com',
    storageBucket: 'watchman-s-gazette.firebasestorage.app',
    measurementId: 'G-ZZEYQ5LRD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNDPIpyo3XqE_woLOcNUuAB_3QrK05to',
    appId: '1:271984737306:android:06cc428141f31f332325a3',
    messagingSenderId: '271984737306',
    projectId: 'watchman-s-gazette',
    storageBucket: 'watchman-s-gazette.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJboCUpPOZx30g4QKIUjKvOhjvVG9jRQ8',
    appId: '1:271984737306:web:044634bdabe402e92325a3',
    messagingSenderId: '271984737306',
    projectId: 'watchman-s-gazette',
    authDomain: 'watchman-s-gazette.firebaseapp.com',
    storageBucket: 'watchman-s-gazette.firebasestorage.app',
    measurementId: 'G-N1W13E6G2C',
  );
}